datasets:
  src_dir: 'input/source'
  src_std_dir: 'input/source_std'
  dest_dir: 'input/destination'
  pose_params_dir: 'input/source'
  mesh_name: 'rp_eric_rigged_001_geo'
  joints:
    - root
    - upperleg_l
    - upperleg_r
    - spine_01
    - lowerleg_l
    - lowerleg_r
    - spine_02
    - foot_l
    - foot_r
    - spine_03
    - ball_l
    - ball_r
    - neck
    - shoulder_l
    - shoulder_r
    - head
    - upperarm_l
    - upperarm_r
    - lowerarm_l
    - lowerarm_r
    - hand_l
    - hand_r

body_model:
  model_type: 'smpl'
  gender: 'neutral'
  ext: 'pkl'
  folder: '../models'

body_part_segm:
  smpl_path: 'config_files/smpl_vert_segmentation.json'
