datasets:
  src_mesh_dir:
    mesh_folder: 'input/source_model'
  src_std_mesh_dir:
    mesh_folder: 'input/source_standard_model'
  dest_mesh_dir:
    mesh_folder: 'input/target_model'
  src_bvh_dir:
    bvh_folder: 'input/source_model'
  dest_bvh_dir:
    bvh_folder: 'input/target_model'
  src_fbx_dir:
    fbx_folder: 'input/source_model'
  dest_fbx_dir:
    fbx_folder: 'input/target_model'

body_model:
  model_type: 'smpl'
  gender: 'neutral'
  ext: 'pkl'
  folder: '../models'

body_part_segm:
  smpl_path: 'config_files/smpl_vert_segmentation.json'
