datasets:
  source_folder:
    mesh_folder: 'input/source_model'
  source_std_folder:
    mesh_folder: 'input/source_standard_model'
  target_folder:
    mesh_folder: 'input/target_model'

body_model:
  model_type: 'smpl'
  gender: 'neutral'
  ext: 'pkl'
  folder: '../models'

body_part_segm:
  smpl_path: 'config_files/smpl_vert_segmentation.json'