datasets:
  src_dir: 'input/source'
  src_std_dir: 'input/source_std'
  dest_dir: 'input/destination'
  pose_params_dir: 'input/source'
  mesh_name: 'H_DDS_HighRes'
  joints:
    - Hips
    - LeftUpLeg
    - RightUpLeg
    - Spine
    - LeftLeg
    - RightLeg
    - Spine1
    - LeftFoot
    - RightFoot
    - Spine2
    - LeftToeBase
    - RightToeBase
    - Neck
    - LeftShoulder
    - RightShoulder
    - Head
    - LeftArm
    - RightArm
    - LeftForeArm
    - RightForeArm
    - LeftHand
    - RightHand

body_model:
  model_type: 'smpl'
  gender: 'neutral'
  ext: 'pkl'
  folder: '../models'

body_part_segm:
  smpl_path: 'config_files/smpl_vert_segmentation.json'
