datasets:
  source_folder:
    mesh_folder: 'input/source_model'
  target_folder:
    mesh_folder: 'input/target_model'

body_model:
  model_type: 'smpl'
  gender: 'neutral'
  ext: 'pkl'
  folder: '../models'