datasets:
  src_dir: 'input/source'
  src_std_dir: 'input/source_std'
  dest_dir: 'input/destination'
  pose_params_dir: 'input/source'

body_model:
  model_type: 'smpl'
  gender: 'neutral'
  ext: 'pkl'
  folder: '../models'

body_part_segm:
  smpl_path: 'config_files/smpl_vert_segmentation.json'
